
#
# Module Manifest for Module 'BlizzWoWRetailGameData.psd1
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Generated: 2025-12-20
#

@{

# Module Loader File
RootModule = 'loader.psm1'

# Version Number
ModuleVersion = '3.19.0'

# Unique Module ID
GUID = '8d6ce216-dc34-46d7-8e17-95a1d763b3e4'

# Module Author
Author = 'Jana Baldszun'

# Company
CompanyName = ''

# Copyright
Copyright = '(c) 2026 Jana Baldszun. All rights reserved.'

# Module Description
Description = 'BlizzWoWRetailGameData is a PowerShell module that provides easy-to-use functions for interacting with Blizzards World of Warcraft Game Data API.

Features:
- Retrieve in-game item, spell, and quest details
- Access realm and auction house data
- Fetch character achievements, statistics, and more
- Designed for automation and scripting in PowerShell

Requirements:
- A valid Blizzard Developer API Key

For documentation and examples, visit: https://develop.battle.net/documentation/world-of-warcraft/game-data-apis
GitHub Repository: https://github.com/JanaBaldszun/BlizzAPIs'

# Minimum PowerShell Version Required
PowerShellVersion = ''

# Name of Required PowerShell Host
PowerShellHostName = ''

# Minimum Host Version Required
PowerShellHostVersion = ''

# Minimum .NET Framework-Version
DotNetFrameworkVersion = ''

# Minimum CLR (Common Language Runtime) Version
CLRVersion = ''

# Processor Architecture Required (X86, Amd64, IA64)
ProcessorArchitecture = ''

# Required Modules (will load before this module loads)
RequiredModules = @()

# Required Assemblies
RequiredAssemblies = @()

# PowerShell Scripts (.ps1) that need to be executed before this module loads
ScriptsToProcess = @()

# Type files (.ps1xml) that need to be loaded when this module loads
TypesToProcess = @()

# Format files (.ps1xml) that need to be loaded when this module loads
FormatsToProcess = @()

# 
NestedModules = @()

# List of exportable functions
FunctionsToExport = '*'

# List of exportable cmdlets
CmdletsToExport = '*'

# List of exportable variables
VariablesToExport = '*'

# List of exportable aliases
AliasesToExport = '*'

# List of all modules contained in this module
ModuleList = @()

# List of all files contained in this module
FileList = @()

# Private data that needs to be passed to this module
PrivateData = ''

}