# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Request-AchievementByID.ps1
. $PSScriptRoot\Request-AchievementCategoriesIndex.ps1
. $PSScriptRoot\Request-AchievementCategoryByID.ps1
. $PSScriptRoot\Request-AchievementIndex.ps1
. $PSScriptRoot\Request-AchievementMedia.ps1
. $PSScriptRoot\Request-AzeriteEssenceByID.ps1
. $PSScriptRoot\Request-AzeriteEssenceMedia.ps1
. $PSScriptRoot\Request-AzeriteEssencesIndex.ps1
. $PSScriptRoot\Request-ConduitByID.ps1
. $PSScriptRoot\Request-ConduitIndex.ps1
. $PSScriptRoot\Request-ConnectedRealmByID.ps1
. $PSScriptRoot\Request-ConnectedRealmIndex.ps1
. $PSScriptRoot\Request-CovenantByID.ps1
. $PSScriptRoot\Request-CovenantIndex.ps1
. $PSScriptRoot\Request-CovenantMedia.ps1
. $PSScriptRoot\Request-CreatureByID.ps1
. $PSScriptRoot\Request-CreatureDisplayMedia.ps1
. $PSScriptRoot\Request-CreatureFamiliesIndex.ps1
. $PSScriptRoot\Request-CreatureFamilyByID.ps1
. $PSScriptRoot\Request-CreatureFamilyMedia.ps1
. $PSScriptRoot\Request-CreatureTypeByID.ps1
. $PSScriptRoot\Request-CreatureTypesIndex.ps1
. $PSScriptRoot\Request-GuildCrestBorderMedia.ps1
. $PSScriptRoot\Request-GuildCrestComponentsIndex.ps1
. $PSScriptRoot\Request-GuildCrestEmblemMedia.ps1
. $PSScriptRoot\Request-HeirloomByID.ps1
. $PSScriptRoot\Request-HeirloomIndex.ps1
. $PSScriptRoot\Request-Realm.ps1
. $PSScriptRoot\Request-RealmIndex.ps1
. $PSScriptRoot\Request-SoulbindByID.ps1
. $PSScriptRoot\Request-SoulbindIndex.ps1
. $PSScriptRoot\Set-WoWApiAccessToken.ps1
. $PSScriptRoot\Set-WoWRegion.ps1
