# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Request-AchievementByID.ps1
. $PSScriptRoot\Request-AchievementCategoriesIndex.ps1
. $PSScriptRoot\Request-AchievementCategoryByID.ps1
. $PSScriptRoot\Request-AchievementIndex.ps1
. $PSScriptRoot\Request-AchievementMedia.ps1
. $PSScriptRoot\Request-AzeriteEssenceByID.ps1
. $PSScriptRoot\Request-AzeriteEssenceMedia.ps1
. $PSScriptRoot\Request-AzeriteEssencesIndex.ps1
. $PSScriptRoot\Request-ConnectedRealmByID.ps1
. $PSScriptRoot\Set-WoWApiAccessToken.ps1
. $PSScriptRoot\Set-WoWRegion.ps1
